global:
  scrape_interval: 5s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
